function createfigure2(X1, YMatrix1)
%CREATEFIGURE(X1,YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 17-Mar-2011 22:59:29

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
box('on');
hold('all');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'LineWidth',2);
set(plot1(1),'DisplayName','Simulation');
set(plot1(2),'DisplayName','Theorical');

% Create xlabel
xlabel('L [m]');

% Create ylabel
ylabel('Pressure Gradient [Pa/m]');

% Create legend
legend(axes1,'show');

