function plot_verticalu(X1, Y1, X2, Y2)
%CREATEFIGURE(X1,Y1,X2,Y2)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 28-Mar-2011 15:51:00

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold('all');

% Create plot
plot(X1,Y1,'DisplayName','Computed','Parent',axes1,'LineWidth',2.5,...
    'LineStyle','--',...
    'Color',[0 0 1]);

% Create plot
plot(X2,Y2,'DisplayName','Erturk et. al. 2008','Parent',axes1,...
    'Marker','diamond',...
    'LineWidth',2.5,...
    'LineStyle','none',...
    'Color',[1 0 0]);

% Create xlabel
xlabel('u-velocity');

% Create ylabel
ylabel('y');

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Position',[0.6854 0.7932 0.2036 0.09333]);

